services:
  sillytavern:
    container_name: sillytavern
    image: ghcr.io/sillytavern/sillytavern:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=101
      cache_from:
        - ghcr.io/sillytavern/sillytavern:cache
      cache_to:
        - type=inline
    hostname: sillytavern
    user: "101:0"
    ports:
      - "8000:8000"
    volumes:
      - "./data:/app/data"
    restart: unless-stopped

  # Reset the password for the default user
  recover:
    extends:
      file: docker-compose.yml
      service: sillytavern
    container_name: sillytavern_recover
    hostname: sillytavern_recover
    profiles:
      - recover
    command: ["recover.js", "default-user", "SHOULD_CHANGE_THIS_PASSWORD"]
    restart: "no"
