services:
  sillytavern:
    container_name: sillytavern
    image: ghcr.io/jim60105/sillytavern:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - UID=1001
      cache_from:
        - ghcr.io/jim60105/sillytavern:cache
      cache_to:
        - type=inline
    user: "1001:0"
    ports:
      - "8000:8000"
    volumes:
      - data:/app/data
    restart: unless-stopped

  # Use this to reset the password for the default user
  sillytavern_recover:
    extends:
      file: docker-compose.yml
      service: sillytavern
    container_name: sillytavern_recover
    profiles:
      - recover
    entrypoint: ["dumb-init", "--", "node", "recover.js"]
    command: ["default-user", "SHOULD_CHANGE_THIS_PASSWORD"]
    restart: "no"

volumes:
  data:
