apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sillytavern.fullname" . }}
  labels: {{- include "sillytavern.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
